---
name: takelage-min
version: 0.1.0

pipelines:
  - prod

images:
  project:
    base_user: takelage
    base_repo: takelslim
    base_tag: latest
    target_user: takelage
    target_repo: init
    omit_pipeline_name: prod
    layers:
      - site

local_user: packer_local
